### ISSUE TITLE
LicenseTemplate ID

### ISSUE THREAD

**Issue by 3052** [ThatNotEasy/FridaFusion#1]
sorry for off topic, but do you know how to get this?

~~~xml
<LicenseTemplate ID="{template_id}" xmlns="">
~~~

**Comment by ThatNotEasy** [comment]
I'm sorry, but I don't understand your question because it's too brief. Could you please explain it in more detail?

**Comment by Ap0dexMe0** [comment]
> sorry for off topic, but do you know how to get this?
> 
> ```
> <LicenseTemplate ID="{template_id}" xmlns="">
> ```

I'm sorry, but I don't understand your question because it's too brief. Could you please explain it in more detail?

**Comment by 3052** [comment]
I am working with playReady, I know how to get key ID but not LicenseTemplate ID

**Comment by Ap0dexMe0** [comment]
> I am working with playReady, I know how to get key ID but not LicenseTemplate ID

I suggest, please dm me privately

**Comment by 3052** [comment]
apid9755@gmail.com? or something else
